/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package toko_buah;
import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author ardi manalu
 */
public class Buah extends javax.swing.JFrame {
    
        private void kosongkan_form(){
            txtnama.setEditable(true);
            txtnama.setText(null);
            txtharga_pokok.setText(null);
            txtid_distributor.setText(null);
            txtexpired.setText(null);
            txtdaerah.setText(null);
            txtjenis.setText(null);
            txtkualitas.setText(null);           
            txtno_transaksi.setText(null);
            txtno_penyimpanan.setText(null);
            txttanggal.setText(null);
            txtstok_buah.setText(null);
            
        }
        private void tampilkan_data(){
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("No.");
            model.addColumn("Nama");
            model.addColumn("Harga_Buah");
            model.addColumn("ID_Distributor");
            model.addColumn("expired");
            model.addColumn("Daerah");
            model.addColumn("Jenis");
            model.addColumn("Kualitas");               
            model.addColumn("NO_Transaksi");
            model.addColumn("NO_Penyimpanan");
            model.addColumn("TANGGAL");
            model.addColumn("STOK");
          
            try{
                int no = 1;
                String sql = "SELECT * FROM tabel_buah";
                java.sql.Connection koneksi = (Connection)Toko_Buah.tokobuahDB();
                java.sql.Statement stm = koneksi.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);
                
                while(res.next()){
                    model.addRow(new Object[]{no++, res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6), res.getString(7), res.getString(8), res.getString(9), res.getString(10), res.getString(11)});
                    
                }
                tabelbuah.setModel(model);
                
                
            }catch(SQLException e) {
                System.out.println("Error : " + e.getMessage());
                
            }
            
            
        }
        
        
    /**
     * Creates new form Buah
     */
    public Buah() {
        initComponents();
        tampilkan_data();
        kosongkan_form();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtharga_pokok = new javax.swing.JTextField();
        txtid_distributor = new javax.swing.JTextField();
        txtexpired = new javax.swing.JTextField();
        txtdaerah = new javax.swing.JTextField();
        txtjenis = new javax.swing.JTextField();
        txtkualitas = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelbuah = new javax.swing.JTable();
        tbtambahdata = new javax.swing.JButton();
        tbsimpan = new javax.swing.JButton();
        tbedit = new javax.swing.JButton();
        tbhapus = new javax.swing.JButton();
        tbkeluar = new javax.swing.JButton();
        tbbatal = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtno_transaksi = new javax.swing.JTextField();
        txtno_penyimpanan = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txttanggal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtstok_buah = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DATA_BUAH");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA BUAH");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Nama ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Harga Buah");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("ID_Distributor");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Expired");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Daerah");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Jenis");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Kualitas");

        txtnama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        txtharga_pokok.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtid_distributor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtexpired.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtdaerah.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtjenis.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtkualitas.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtkualitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkualitasActionPerformed(evt);
            }
        });

        tabelbuah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelbuah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbuahMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelbuah);

        tbtambahdata.setText("Tambah Data");
        tbtambahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtambahdataActionPerformed(evt);
            }
        });

        tbsimpan.setText("Simpan");
        tbsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbsimpanActionPerformed(evt);
            }
        });

        tbedit.setText("Edit");
        tbedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbeditActionPerformed(evt);
            }
        });

        tbhapus.setText("Hapus");
        tbhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbhapusActionPerformed(evt);
            }
        });

        tbkeluar.setText("Kembali");
        tbkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbkeluarActionPerformed(evt);
            }
        });

        tbbatal.setText("Batal");
        tbbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbbatalActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("NO_Transaksi");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("NO_Penyimpanan");

        txtno_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtno_transaksiActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Tanggal");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("STOK");

        jLabel13.setText("Kg");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtkualitas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtnama, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                .addComponent(txtharga_pokok, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtid_distributor, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(txtno_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtstok_buah, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtjenis, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(txtdaerah)
                            .addComponent(txtexpired)
                            .addComponent(txttanggal)
                            .addComponent(txtno_penyimpanan))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tbedit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbbatal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbkeluar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbtambahdata, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addGap(230, 230, 230))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tbsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)
                                .addComponent(tbhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtexpired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tbedit)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtharga_pokok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtdaerah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtid_distributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addComponent(jLabel7)
                            .addComponent(txtjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(tbbatal)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(tbtambahdata))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtkualitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12))
                            .addComponent(txttanggal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tbkeluar)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtstok_buah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbsimpan)
                            .addComponent(tbhapus)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtno_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtno_penyimpanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void tbkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbkeluarActionPerformed
        // TODO add your handling code here:
        
         this.setVisible(false);
        new Menu().setVisible(true);
        
    }//GEN-LAST:event_tbkeluarActionPerformed

    private void txtkualitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkualitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkualitasActionPerformed

    private void tbtambahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtambahdataActionPerformed
        // TODO add your handling code here:
        kosongkan_form();
    }//GEN-LAST:event_tbtambahdataActionPerformed

    private void tbsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbsimpanActionPerformed
        // TODO add your handling code here:
        
        try{
             String sql ;             
            java.sql.Connection koneksi = (Connection)Toko_Buah.tokobuahDB();             
            sql = "INSERT INTO tabel_buah VALUES ('" +txtnama.getText()+"','" +txtharga_pokok.getText()+"','" +txtid_distributor.getText()+"','" +txtexpired.getText()+"','" +txtdaerah.getText()+"','" +txtjenis.getText()+"','" +txtkualitas.getText()+"','" +txtno_transaksi.getText()+"','" +txtno_penyimpanan.getText()+"','" +txttanggal.getText()+"','"+txtstok_buah.getText() +"')";
            java.sql.PreparedStatement pstm = koneksi.prepareStatement(sql); 
            pstm.execute();
            tampilkan_data();
            
            sql = "INSERT INTO gudang VALUES ('" +txtno_penyimpanan.getText()+"','"+txtjenis.getText() +"','" + txtstok_buah.getText()+ "')";            
            java.sql.PreparedStatement pstms = koneksi.prepareStatement(sql);
            pstms.execute();
            sql = "INSERT INTO transaksi VALUES ('"+txtno_transaksi.getText()+"','"+txtnama.getText()+"','"+txtharga_pokok.getText()+"','"+txttanggal.getText()+ "')";            
            java.sql.PreparedStatement pstmss = koneksi.prepareStatement(sql);
            pstmss.execute();
            sql = "INSERT INTO distributor VALUES ('"+txtid_distributor.getText()+"','"+txtnama.getText()+"','"+txtdaerah.getText()+"','"+txttanggal.getText()+ "')";            
            java.sql.PreparedStatement pstmsss = koneksi.prepareStatement(sql);
            pstmsss.execute();
            JOptionPane.showMessageDialog(null, "Proses Simpan Data Berhasil...");            
            kosongkan_form();                      
        }catch ( HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this , e.getMessage());
            
        }
            
    }//GEN-LAST:event_tbsimpanActionPerformed

    private void tabelbuahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbuahMouseClicked
        // TODO add your handling code here:
        int baris = tabelbuah.rowAtPoint(evt.getPoint());
        String nama = tabelbuah.getValueAt(baris, 1).toString();
        txtnama.setText(nama);
        
        String harga_buah = tabelbuah.getValueAt(baris, 2).toString();
        txtharga_pokok.setText(harga_buah);
        
        String id_distributor = tabelbuah.getValueAt(baris, 3).toString();
        txtid_distributor.setText(id_distributor);
        
        String expired = tabelbuah.getValueAt(baris, 4).toString();
        txtexpired.setText(expired);
        
        String daerah = tabelbuah.getValueAt(baris, 5).toString();
        txtdaerah.setText(daerah);
        
        String jenis = tabelbuah.getValueAt(baris, 6).toString();
        txtjenis.setText(jenis);
        
        String kualitas = tabelbuah.getValueAt(baris, 7).toString();
        txtkualitas.setText(kualitas);        
               
        String no_transaksi = tabelbuah.getValueAt(baris, 8).toString();
        txtno_transaksi.setText(no_transaksi);
        
        String no_penyimpanan = tabelbuah.getValueAt(baris,9).toString();
        txtno_penyimpanan.setText(no_penyimpanan); 
        
        String tanggal = tabelbuah.getValueAt(baris, 10).toString();
        txttanggal.setText(tanggal);
        
         String stok = tabelbuah.getValueAt(baris,11).toString();
        txtstok_buah.setText(stok); 
        
    }//GEN-LAST:event_tabelbuahMouseClicked

    private void tbeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbeditActionPerformed
        // TODO add your handling code here:
        try{
            
            String sql ="UPDATE tabel_buah set nama='" +txtnama.getText()+"',harga_pokok='" +txtharga_pokok.getText()+"',id_distributor='" +txtid_distributor.getText()+"',expired='" +txtexpired.getText()+"',daerah='" +txtdaerah.getText()+"',jenis='" +txtjenis.getText()+"',kualitas='" +txtkualitas.getText()+"',NO_Transaksi='" +txtno_transaksi.getText()+"',NO_Penyimpanan='" +txtno_penyimpanan.getText()+"',tanggal='" +txttanggal.getText()+"',Stok='"+txtstok_buah.getText() +"'WHERE nama= '"+txtnama.getText()+"'";
            java.sql.Connection koneksi = (Connection)Toko_Buah.tokobuahDB();
            java.sql.PreparedStatement pstm = koneksi.prepareStatement(sql);
            pstm.execute();
            
            sql = "UPDATE gudang set no_penyimpanan='"+txtno_penyimpanan.getText()+"',jenis='"+txtjenis.getText()+"',stok='"+txtstok_buah.getText() +"'WHERE no_penyimpanan= '"+txtno_penyimpanan.getText()+"'";            
            java.sql.PreparedStatement pstms = koneksi.prepareStatement(sql);
            pstms.execute();
            sql = "UPDATE transaksi set no_transaksi='"+txtno_transaksi.getText()+"',nama='"+txtnama.getText()+"',harga_pokok='"+txtharga_pokok.getText()+"',tanggal='"+txttanggal.getText()+ "'WHERE no_transaksi= '"+txtno_transaksi.getText()+"'";         
            java.sql.PreparedStatement pstmss = koneksi.prepareStatement(sql);
            pstmss.execute();
            sql = "UPDATE tabel_buah set id_distributor='"+txtid_distributor.getText()+"',nama='"+txtnama.getText()+"',daerah='"+txtdaerah.getText()+"',tanggal='"+txttanggal.getText()+ "'WHERE id_distributor= '"+txtid_distributor.getText()+"'";            
            java.sql.PreparedStatement pstmsss = koneksi.prepareStatement(sql);
            pstmsss.execute();
            JOptionPane.showMessageDialog(null , "Edit Data Berhasil... ");                                    
            
        }catch ( HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this , e.getMessage());            
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_tbeditActionPerformed

    private void tbhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbhapusActionPerformed
        // TODO add your handling code here:
        try{
            
            String sql = "DELETE FROM tabel_buah WHERE nama='"+txtnama.getText()+"'";
            java.sql.Connection koneksi = (Connection)Toko_Buah.tokobuahDB();
            java.sql.PreparedStatement pstm = koneksi.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null , "Hapus Data Berhasil... ");
                
        }catch ( HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this , e.getMessage());            
        }
        tampilkan_data();
        kosongkan_form();
        
        
    }//GEN-LAST:event_tbhapusActionPerformed

    private void tbbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbbatalActionPerformed
        // TODO add your handling code here:
        kosongkan_form();
    }//GEN-LAST:event_tbbatalActionPerformed

    private void txtno_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtno_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtno_transaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelbuah;
    private javax.swing.JButton tbbatal;
    private javax.swing.JButton tbedit;
    private javax.swing.JButton tbhapus;
    private javax.swing.JButton tbkeluar;
    private javax.swing.JButton tbsimpan;
    private javax.swing.JButton tbtambahdata;
    private javax.swing.JTextField txtdaerah;
    private javax.swing.JTextField txtexpired;
    private javax.swing.JTextField txtharga_pokok;
    private javax.swing.JTextField txtid_distributor;
    private javax.swing.JTextField txtjenis;
    private javax.swing.JTextField txtkualitas;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtno_penyimpanan;
    private javax.swing.JTextField txtno_transaksi;
    private javax.swing.JTextField txtstok_buah;
    private javax.swing.JTextField txttanggal;
    // End of variables declaration//GEN-END:variables
}
